package co.edu.unicauca.gui.vistas.articulos;

import co.edu.unicauca.gui.models.Articulo;
import co.edu.unicauca.gui.models.Conferencia;
import co.edu.unicauca.gui.servicios.ArticuloServices;
import java.util.stream.Collectors;

/**
 *
 * @author sonhuila
 */
public class VtnConsultarArticulo extends javax.swing.JInternalFrame {

    private ArticuloServices objArticuloServices;

    public VtnConsultarArticulo(ArticuloServices objArticuloServices) {
        initComponents();
        this.objArticuloServices = objArticuloServices;
        this.jLabelMostrarMensaje.setVisible(false);
        this.jPanelMostrarDatos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelInferior = new javax.swing.JPanel();
        jPanelMedio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIdArticulo = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jLabelMostrarMensaje = new javax.swing.JLabel();
        jPanelMostrarDatos = new javax.swing.JPanel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelAutores = new javax.swing.JLabel();
        jLabelResumen = new javax.swing.JLabel();
        jLabelIdArticulo = new javax.swing.JLabel();
        jLabelMAutores = new javax.swing.JLabel();
        jLabelMResumen = new javax.swing.JLabel();
        jLabelMIdArticulo = new javax.swing.JLabel();
        jLabelMNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConferencias = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 51, 255));
        jLabelTitulo.setText("Consultar articulo");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabelTitulo)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelTitulo)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelInferior, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Id");

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelMostrarMensaje.setText("Mensaje");

        jPanelMostrarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombre1.setText("Nombre:");

        jLabelAutores.setText("Autores:");

        jLabelResumen.setText("Resumen:");

        jLabelIdArticulo.setText("Id Articulo");

        jLabelMAutores.setText("resultado");

        jLabelMResumen.setText("resultado");

        jLabelMIdArticulo.setText("resultado");

        jLabelMNombre.setText("resultado");

        javax.swing.GroupLayout jPanelMostrarDatosLayout = new javax.swing.GroupLayout(jPanelMostrarDatos);
        jPanelMostrarDatos.setLayout(jPanelMostrarDatosLayout);
        jPanelMostrarDatosLayout.setHorizontalGroup(
            jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre1)
                    .addComponent(jLabelAutores)
                    .addComponent(jLabelResumen)
                    .addComponent(jLabelIdArticulo))
                .addGap(108, 108, 108)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMResumen)
                    .addComponent(jLabelMAutores)
                    .addComponent(jLabelMNombre)
                    .addComponent(jLabelMIdArticulo))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanelMostrarDatosLayout.setVerticalGroup(
            jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarDatosLayout.createSequentialGroup()
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelMIdArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMNombre)
                        .addGap(16, 16, 16)
                        .addComponent(jLabelMAutores)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelMResumen))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarDatosLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jLabelIdArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNombre1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelAutores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelResumen)))
                .addGap(28, 28, 28))
        );

        jTextAreaConferencias.setColumns(20);
        jTextAreaConferencias.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConferencias);

        javax.swing.GroupLayout jPanelMedioLayout = new javax.swing.GroupLayout(jPanelMedio);
        jPanelMedio.setLayout(jPanelMedioLayout);
        jPanelMedioLayout.setHorizontalGroup(
            jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMostrarMensaje)
                    .addGroup(jPanelMedioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonConsultar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMedioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanelMedioLayout.setVerticalGroup(
            jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabelMostrarMensaje)
                .addGap(18, 18, 18)
                .addGroup(jPanelMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelMostrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMedio, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        String idArticulo;
        Integer idArticuloEntero;
        idArticulo = this.jTextFieldIdArticulo.getText();
        idArticuloEntero = Integer.parseInt(idArticulo);

        if (this.objArticuloServices.consultarSiExisteArticulo(idArticuloEntero)) {
            this.jLabelMostrarMensaje.setVisible(false);
            this.jPanelMostrarDatos.setVisible(true);
            Articulo objArticulo = this.objArticuloServices.consultarArticulo(idArticuloEntero);
            this.jLabelMIdArticulo.setText(objArticulo.getIdArticulo() + "");
            this.jLabelMNombre.setText(objArticulo.getTitulo());
            this.jLabelMAutores.setText(objArticulo.getAutores());
            this.jLabelMResumen.setText(objArticulo.getResumen() + "");
            // Convertir la lista de Conferencia a una lista de Strings con el nombre de cada conferencia
            String conferenciasTexto = objArticulo.getConferencias().stream()
                    .map(Conferencia::getNombre) // Asumiendo que getNombre devuelve el nombre de la conferencia
                    .collect(Collectors.joining(", "));

                    // Mostrar el texto en el JTextArea o JLabel
                     this.jTextAreaConferencias.setText(conferenciasTexto);
        } else {
            this.jLabelMostrarMensaje.setVisible(true);
            this.jLabelMostrarMensaje.setText("Error, no existe un articulo con ese identificador");
            this.jPanelMostrarDatos.setVisible(false);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutores;
    private javax.swing.JLabel jLabelIdArticulo;
    private javax.swing.JLabel jLabelMAutores;
    private javax.swing.JLabel jLabelMIdArticulo;
    private javax.swing.JLabel jLabelMNombre;
    private javax.swing.JLabel jLabelMResumen;
    private javax.swing.JLabel jLabelMostrarMensaje;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelResumen;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelMedio;
    private javax.swing.JPanel jPanelMostrarDatos;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConferencias;
    private javax.swing.JTextField jTextFieldIdArticulo;
    // End of variables declaration//GEN-END:variables
}
